import Head from 'next/head'
import React from 'react'
import { Editor } from '@tiptap/react'
import { Inter } from '@next/font/google'
import Navbar from '../../components/navbar';
import SelectCategories from '../../components/categories/select';
import Tiptap from '../../components/tiptap'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function NewArticle() {

    const router = useRouter()

    const handleSubmit = event => {
        
        event.preventDefault()

        const formData = new FormData();

        formData.append("categoryId", document.querySelector('#category_id').value);
        formData.append("title", document.querySelector('#title').value);
        formData.append("content", document.querySelector('#content > div').innerHTML);
        
        fetch(`${process.env.API_URL}articles`, {
            method: 'POST',
            body: formData
        })

        return router.push('/articles')  
    }
  return (
    <>
      <Head>
      <title>Notification App - New Article</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Navbar />
        
        <main className="flex justify-center py-20">
            <div className="w-full max-w-5xl">
                <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" onSubmit={handleSubmit}>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Category
                        </label>
                        <select className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="category_id" name="category_id" required>
                            <SelectCategories />
                        </select>
                    </div>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Title
                        </label>
                        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="title" name="title" type="text" required />
                    </div>
                    <div className="mb-6">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Content
                        </label>
                        <Tiptap />
                    </div>
                    <div className="flex items-center justify-between">
                    <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        Send
                    </button>
                    </div>
                </form>
            </div>
        </main>
    </>
  )
}
