import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import Navbar from '../../components/navbar';
import ListCategories from '../../components/categories/list';

const inter = Inter({ subsets: ['latin'] })

export default function Categories( ) {
    return (
    <>
        <Head>
            <title>Notification App - Categories</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Navbar />

        <ListCategories />
    </>
    )
}
