import Head from 'next/head'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import Navbar from '../../components/navbar';
import ListUsers from '../../components/users/list';

const inter = Inter({ subsets: ['latin'] })

export default function Users( ) {
    return (
    <>
        <Head>
            <title>Notification App - Usuarios</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        
        <Navbar />

        <main className="mb-4 py-10 max-w-7xl mx-auto">
            <Link href="/users/new" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">
                New User
            </Link>
        </main>

        <ListUsers />
    </>
    )
}