import Head from 'next/head'
import React from 'react'
import { Editor } from '@tiptap/react'
import { Inter } from '@next/font/google'
import Navbar from '../../components/navbar';
import CheckboxCategories from '../../components/categories/checkbox';
import CheckboxChannels from '../../components/channels/checkbox';
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function NewUser() {

    const router = useRouter()

    const handleSubmit = event => {
        
        event.preventDefault()

        const formData = new FormData();

        let subscribed = [];
        let channels = [];

        formData.append("name", document.querySelector('#name').value);
        formData.append("email", document.querySelector('#email').value);
        formData.append("phoneNumber", document.querySelector('#phoneNumber').value);

        console.log(document.querySelectorAll('input[name=categories]:checked'));


        document.querySelectorAll('.checkbox-categories').forEach(function(checkbox) {
            if (checkbox.checked) {            
                subscribed.push(checkbox.value)
            }
        });
        
        document.querySelectorAll('.checkbox-channels').forEach(function(checkbox) {
            if (checkbox.checked) {            
                channels.push(checkbox.value)
            }
        });

        formData.append("subscribed", subscribed);
        formData.append("channels", channels);
       
        fetch(`${process.env.API_URL}users`, {
            method: 'POST',
            body: formData
        })

        return router.push('/users')  
    }
    
  return (
    <>
      <Head>
      <title>Notification App - New User</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Navbar />
        
        <main className="flex justify-center py-20">
            <div className="w-full max-w-5xl">
                <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" onSubmit={handleSubmit}>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Name
                        </label>
                        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="name" name="name" type="text" required />
                    </div>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Email
                        </label>
                        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" name="email" type="email" required />
                    </div>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Phone Number
                        </label>
                        <input className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="phoneNumber" name="phoneNumber" type="text" required />
                    </div>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Suscribed
                        </label>
                        <CheckboxCategories />
                    </div>
                    <div className="mb-4">
                        <label className="block text-gray-700 text-sm font-bold mb-2">
                            Channels
                        </label>
                        <CheckboxChannels />
                    </div>
                    <div className="flex items-center justify-between">
                    <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                        Send
                    </button>
                    </div>
                </form>
            </div>
        </main>
    </>
  )
}
