import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '../components/navbar';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Notification App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
    <Navbar />
      <main className="flex flex-wrap mb-4 py-20 max-w-7xl mx-auto">
        <Link href="/articles" className="w-1/2 max-w-sm rounded overflow-hidden shadow-lg">
            <div className="px-6 py-4">
                <h1 className="font-bold text-xl mb-2">List of Articles</h1>
            </div>
        </Link>
        <Link href="/categories" className="w-1/2 max-w-sm rounded overflow-hidden shadow-lg">
            <div className="px-6 py-4">
                <h1 className="font-bold text-xl mb-2">List of Categories</h1>
            </div>
        </Link>
        <Link href="/users" className="w-1/2 max-w-sm rounded overflow-hidden shadow-lg">
            <div className="px-6 py-4">
                <h1 className="font-bold text-xl mb-2">List of Users</h1>
            </div>
        </Link>
      </main>
    </>
  )
}
